### ISSUE TITLE
EdgeTable as Table?

### ISSUE THREAD

**Issue by tonywong94** [tonywong94/edge_pydb#14]
Why doesn't this command work?

cofile = EdgeTable('NGC4047.comom_smo7.hdf5', path='smo')
print(cofile.colnames)

It would be nice if somehow the EdgeTable could be treated like an Astropy Table.  So print(cofile) would show the full table (or an abbreviated version).  I think, in Python speak, that EdgeTable should be a child of Table.

**Comment by Brookluo** [comment]
This is due to that I implemented an independent class EdgeTable rather than implementing a child class and inherit functions from Table. I'll look into that and check inheritance of the astropy Table functions

**Comment by Brookluo** [comment]
This issue should have been solved in the new PR, thanks.
