### ISSUE TITLE
Error when site-packages is read-only

### ISSUE THREAD

**Issue by tonywong94** [tonywong94/edge_pydb#4]
The program is crashing because my site-packages area is read-only.  The code should emit a warning if the file cannot be modified, but it should not crash.

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/site-packages/edge_pydb/__init__.py in <module>()
     13 try:
---> 14     _fp = open(_filepath, 'r+')
     15     _config = _json.load(_fp)

OSError: [Errno 30] Read-only file system: '/home/jovyan/site-packages/edge_pydb/_config.json'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-2-c782cdc0ef9c> in <module>()
      1 import sys
      2 sys.path.append('/home/jovyan/site-packages')
----> 3 from edge_pydb import getfiles
      4 califa = Table.read(getfiles('edge_califa.csv'), format='ascii.ecsv')  # CALIFA params incl. distance
      5 db1 = join(pipe3d_dist, califa, keys='Name')

~/site-packages/edge_pydb/__init__.py in <module>()
     16 
     17 except:
---> 18     _fp = open(_filepath, 'w')
     19     _config = {}
     20 

OSError: [Errno 30] Read-only file system: '/home/jovyan/site-packages/edge_pydb/_config.json'

**Comment by Brookluo** [comment]
This issue should have been solved with the updated file permission check. If the user's file system is read-only, then the package will not update the configuration file, but rather keep the location of the files inside the runtime dictionary, and therefore the location of the file will only be remembered in the session.
